package com.example.backtest.model

import java.time.LocalDateTime

/**
 * Supported signal types for the backtesting engine.
 */
enum class SignalType {
    LONG,   // Entry for Long position
    SHORT,  // Entry for Short position
    EXIT    // Exit current position (Long or Short)
}

/**
 * Represents a signal generated by a strategy at a specific point in time.
 */
data class Signal(
    val type: SignalType,
    val timestamp: LocalDateTime,
    val price: Double,
    val metadata: Map<String, Any> = emptyMap()
)
